version: 2
updates:
- package-ecosystem: composer
  directory: "/html"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/html"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
