name: Deploy
on:
  push:
    branches:
      - main
    paths:
      - 'html/src/**'
      - 'html/templates/**'
      - 'html/webroot/css/**'
      - 'html/webroot/js/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.VPS_REPO_PATH }}
            git pull origin main
            #cp -r "${{ secrets.VPS_REPO_PATH }}/src/" "${{ secrets.VPS_DEPLOY_PATH }}/"
            #cp -r "${{ secrets.VPS_REPO_PATH }}/templates/" "${{ secrets.VPS_DEPLOY_PATH }}/"
            #cp -r "${{ secrets.VPS_REPO_PATH }}/webroot/js/" "${{ secrets.VPS_DEPLOY_PATH }}/webroot/"
            #cp -r "${{ secrets.VPS_REPO_PATH }}/webroot/css/" "${{ secrets.VPS_DEPLOY_PATH }}/webroot/"
