name: Deploy
on:
  push:
    branches:
      - main
    paths:
      - 'html/src/**'
      - 'html/templates/**'
      - 'html/webroot/css/**'
      - 'html/webroot/js/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SSH Key for Deploy
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.VPS_REPO_PATH }}
            git pull origin main

            deploy_targets=(
              templates/src
              templates/templates
              webroot/css
              webroot/js
            )
            for path in "${deploy_targets[@]}"; do
              cp -r "${{ secrets.VPS_REPO_PATH }}/html/$path/*" "${{ secrets.VPS_DEPLOY_PATH }}/$path/"
            done
